# docker-compose.dev.yml

flask-dev:
  restart: always
  build: ./app
  working_dir: /app
  volumes:
    - ./app:/app
  env_file:
    - ./envs/dev.env
  ports:
    - '5000:5000'
  command: python run.py