# docker-compose.prd.yml

nginx-server:
  restart: always
  image: nginx
  volumes:
    - ./server/conf.d:/etc/nginx/conf.d
    - ./app/static:/app/static
  links:
    - flask-prd:flask-prd
  ports:
    - "80:80"

flask-prd:
  restart: always
  build: ./app
  env_file:
    - ./envs/prd.env
  expose:
    - "8000"
  command: gunicorn run:app -b :8000
  # command: gunicorn run:app -b :8000 --name app --log-level=debug --log-file=-